INSERT INTO cliente(nome, data_nasc, telefone, num_passaporte) VALUES ("Monkey D. Luffy", "1996-12-25", "(11)1234-5678", "BR000001");
INSERT INTO cliente(nome, data_nasc, telefone, num_passaporte) VALUES ("Naruto Uzumaki", "1990-04-01", "(11)1234-5678", "BR000002");
INSERT INTO cliente(nome, data_nasc, telefone, num_passaporte) VALUES ("Tajiro Kamada", "1998-10-21", "(11)1234-5678", "BR000003");
INSERT INTO cliente(nome, data_nasc, telefone, num_passaporte) VALUES ("Yusuke Urameshi", "1987-01-31", "(11)1234-5678", "BR000004");
INSERT INTO cliente(nome, data_nasc, telefone, num_passaporte) VALUES ("Kagome Higurashi", "1996-11-24", "(11)1234-5678", "BR000005");

INSERT INTO Destino(nome, valor, descricao, descricao_completa, desconto, img, tipo) VALUES ("Rio de Janeiro", 705, "Rio de Janeiro, beleza que inspira.", "O Rio de Janeiro, cidade maravilhosa do Brasil, encanta com suas praias deslumbrantes, montanhas majestosas, e um carnaval contagiante, proporcionando uma experiência única e apaixonante aos visitantes.", 7, "https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/urca.jpg","NACIONAL");

INSERT INTO Destino(nome, valor, descricao, descricao_completa, desconto, img, tipo) VALUES ("Seoul", 10675, "Seoul, a cidade das mil faces e infinitas possibilidades.", "Seoul, uma metrópole eletrizante que combina tradição e modernidade, oferecendo uma rica tapeçaria cultural, tecnológica e gastronômica, que hipnotiza e encanta seus visitantes.", 20, "https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/seoul.jpg","INTERNACIONAL");

INSERT INTO Destino(nome, valor, descricao, descricao_completa, desconto, img, tipo) VALUES ("Salvador",866,"Salvador, onde história e encanto se encontram.","Salvador, a cidade do axé e da cultura afro-brasileira, encanta com suas praias deslumbrantes, arquitetura colonial colorida e festas animadas, emanando uma energia contagiante em cada esquina.",7,"https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/salvador.jpg","NACIONAL");

INSERT INTO Destino(nome, valor, descricao, descricao_completa, desconto, img, tipo) VALUES ("São Francisco",4180,"São Francisco, cidade da Califórnia encantadora.","São Francisco, cidade vibrante na costa oeste dos EUA, é famosa pela icônica Golden Gate Bridge, cenário tecnológico e cultura diversificada, proporcionando uma experiência cativante e inesquecível aos seus visitantes.",15,"https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/sanfrancisco.jpg","INTERNACIONAL");

INSERT INTO Destino(nome, valor, descricao, descricao_completa, desconto, img, tipo) VALUES ("Sidney",9275,"Sydney, a deslumbrante cidade australiana.","Sydney, a espetacular metrópole australiana, que combina praias de tirar o fôlego, uma arquitetura moderna e icônica, além de uma vida cultural vibrante, tornando-se uma das cidades mais fascinantes e desejadas do mundo.",20,"https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/sidney.jpg","INTERNACIONAL");

INSERT INTO Destino(nome, valor, descricao, descricao_completa, desconto, img, tipo) VALUES ("Mariana",874,"Mariana, uma encantadora cidade mineira.","Mariana, cidade histórica de Minas Gerais, fascina com suas igrejas barrocas preservadas, casarões coloniais e paisagens pitorescas, transportando os visitantes para um passado encantador do Brasil colonial.",5,"https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/mariana.jpg","NACIONAL");

INSERT INTO Destino(nome, valor, descricao, descricao_completa, desconto, img, tipo) VALUES ("Curitiba",483,"Curitiba, verdejante metrópole com rica cultura brasileira.","Curitiba, a capital ecológica do Brasil, encanta com seus parques bem-cuidados, sistema de transporte eficiente e uma rica cena cultural, oferecendo uma qualidade de vida invejável aos seus moradores.",5,"https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/curitiba.jpg","NACIONAL");

INSERT INTO Destino(nome, valor, descricao, descricao_completa, desconto, img, tipo) VALUES ("Recife",1596,"Recife, cidade encantadora do Nordeste brasileiro.","Recife, a joia do Nordeste brasileiro, encanta com suas praias de águas mornas e coqueirais, sua rica história que mescla tradição e modernidade, e a alegria contagiante de seu povo, sempre acolhedor e vibrante.",10,"https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/recife.jpg","NACIONAL");

INSERT INTO Destino(nome, valor, descricao, descricao_completa, desconto, img, tipo) VALUES ("Paris",4716,"Paris, a cidade luz do romantismo e da cultura.","Paris, a romântica Cidade Luz, cativa com seus ícones icônicos como a Torre Eiffel e o Louvre, além de uma cultura sofisticada e gastronomia refinada, tornando-se um destino inesquecível para os apaixonados por arte, história e charme.",13,"https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/paris.jpg","INTERNACIONAL");

INSERT INTO Destino(nome, valor, descricao, descricao_completa, desconto, img, tipo) VALUES ("Londres",5347,"Londres, a metrópole multicultural e cheia de história.","Londres, a capital britânica, brilha com uma rica tapeçaria de história e modernidade, destacando-se com seus marcos emblemáticos, cultura diversificada e dinâmica cena artística, tornando-se uma cidade perfeita para explorar.",10,"https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/london.jpg","INTERNACIONAL");

INSERT INTO Destino(nome, valor, descricao, descricao_completa, desconto, img, tipo) VALUES ("Tóquio",7547,"Tóquio, metrópole futurista e vibrante do Japão.","Tóquio, combina modernidade e tradição em uma harmoniosa fusão. Seus arranha-céus reluzentes, templos ancestrais e cultura pop enérgica encantam os visitantes do mundo todo, oferecendo uma experiência única e inesquecível.",15,"https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/tokyo.jpg","INTERNACIONAL");

INSERT INTO Destino(nome, valor, descricao, descricao_completa, desconto, img, tipo) VALUES ("Maranhão",1856,"São Luís, cidade histórica e culturalmente rica.","São Luís, capital do Maranhão, é um tesouro histórico com sua arquitetura colonial preservada e rica herança cultural. Suas praias exuberantes e gastronomia típica completam a experiência encantadora.",10,"https://raw.githubusercontent.com/RabbitDeWitt/Atividade-Modulo-2/master/site/assets/imgs/maranhao.jpg","NACIONAL");

INSERT INTO Pacote(nome, valor) VALUES ("Economica", 0);
INSERT INTO Pacote(nome, valor) VALUES ("Economica Premium", 400);
INSERT INTO Pacote(nome, valor) VALUES ("Executiva", 1500);
INSERT INTO Pacote(nome, valor) VALUES ("Primeira classe", 5000);
